### ISSUE TITLE
Time Out Error

### ISSUE THREAD

**Issue by Nilsser** [ImageMarkup/isic-cli#11]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.

This is a bug in isic-cli and should be reported. You can open an issue below:

**Comment by danlamanna** [comment]
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.
> 
> This is a bug in isic-cli and should be reported. You can open an issue below: 
> 
> 

Could you paste the diagnostic information beneath. In particular, which version and command are you running?

**Comment by Nilsser** [comment]
Sure, Im sorry I forgot to provide this Information, I'm new to Github.

`The following unexpected error occurred while attempting your operation:

Traceback (most recent call last):
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    yield
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\urllib3\response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\nilss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\nilss\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\nilss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\nilss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\models.py", line 816, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\urllib3\response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\urllib3\response.py", line 515, in read
    with self._error_catcher():
  File "C:\Users\nilss\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\urllib3\response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\isic_cli\cli\__init__.py", line 132, in main
    cli()
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\isic_cli\cli\utils.py", line 17, in decorator
    f(ctx, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\isic_cli\cli\image.py", line 102, in download
    for image in images_iterator:
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\isic_cli\io\http.py", line 98, in get_images
    r = session.get(next_page)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\isic_cli\session.py", line 39, in request
    r = super().request(*args, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\retryable_requests\session.py", line 35, in request
    return super().request(*args, **kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests_toolbelt\sessions.py", line 64, in request
    return super(BaseUrlSession, self).request(
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\sessions.py", line 745, in send
    r.content
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\models.py", line 900, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "c:\users\nilss\pycharmprojects\pythonproject1\venv\lib\site-packages\requests\models.py", line 823, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.

isic-cli: v3.0.0
python:   v3.10.5
time:     2022-06-18T19:53:59.526880
os:       Windows-10-10.0.19043-SP0
env:      -
user:     -
command:  isic image download -l 0 images/

`

**Comment by danlamanna** [comment]
This is surprising, the command should be doing a lot of retries internally to prevent this from happening. Though frustrating, the short term solution is to run the command again  - it should pick up where it left off.

**Comment by Nilsser** [comment]
Sadly, It seems to restart from new everytime and run into the same error.

Could a faster Internetconnection help?

Or is there a Kaggle link to this exact Trainingsset?

**Comment by danlamanna** [comment]
> Could a faster Internetconnection help?

Yes, it's possible the internet connection is so slow it gives up.

> Or is there a Kaggle link to this exact Trainingsset?

I'm not sure which dataset you're looking for. All of the prepackaged datasets for challenges are available at https://challenge.isic-archive.com/data/.
