### ISSUE TITLE
bug in isic-cli

### ISSUE THREAD

**Issue by nuzhat-promi** [ImageMarkup/isic-cli#28]
I tried to download isic-archive images using `isic image download images` command. But exception occurred and the message was to report the issue here.
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.`
```
isic-cli: v4.2.0
python:   v3.9.12
time:     2022-12-20T12:08:56.821809
os:       Windows-10-10.0.19045-SP0
env:      -
user:     -
command:  isic image download images
```
Then I tried logging in my account and it was successful. But when I attempted download, it showed the same meaasge. Can anyone fix the bug and/or tell me what am I doing wrong? Thank you!

**Comment by nuzhat-promi** [comment]
My whole error report. Any help would be appreciated. THank you!
```
Downloading metadata records (71,670) -- -------------------------------------   6% 1:35:14
The following unexpected error occurred while attempting your operation:

Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    yield
  File "E:\anaconda3\lib\site-packages\urllib3\response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "E:\anaconda3\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "E:\anaconda3\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "E:\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "E:\anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "E:\anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\requests\models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "E:\anaconda3\lib\site-packages\urllib3\response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "E:\anaconda3\lib\site-packages\urllib3\response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "E:\anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\anaconda3\lib\site-packages\urllib3\response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\isic_cli\cli\__init__.py", line 132, in main
    cli()
  File "E:\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "E:\anaconda3\lib\site-packages\isic_cli\cli\utils.py", line 17, in decorator
    f(ctx, **kwargs)
  File "E:\anaconda3\lib\site-packages\isic_cli\cli\metadata.py", line 155, in download
    headers, records = _extract_metadata(images, progress, task)
  File "E:\anaconda3\lib\site-packages\isic_cli\cli\utils.py", line 46, in _extract_metadata
    for image in images:
  File "E:\anaconda3\lib\site-packages\isic_cli\io\http.py", line 94, in get_images
    r = session.get(next_page)
  File "E:\anaconda3\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "E:\anaconda3\lib\site-packages\isic_cli\session.py", line 39, in request
    r = super().request(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\retryable_requests\session.py", line 35, in request
    return super().request(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\requests_toolbelt\sessions.py", line 76, in request
    return super(BaseUrlSession, self).request(
  File "E:\anaconda3\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda3\lib\site-packages\requests\sessions.py", line 687, in send
    r.content
  File "E:\anaconda3\lib\site-packages\requests\models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "E:\anaconda3\lib\site-packages\requests\models.py", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.isic-archive.com', port=443): Read timed out.

isic-cli: v4.2.0
python:   v3.9.12
time:     2022-12-24T06:55:03.188279
os:       Windows-10-10.0.19045-SP0
env:      -
user:     -
command:  isic metadata download

This is a bug in isic-cli and should be reported. You can open an issue below:
https://github.com/ImageMarkup/isic-cli/issues/new
```

**Comment by danlamanna** [comment]
This looks like the network is being a bit unreliable. I released a new version that should be more aggressive about retrying failed requests. If you can upgrade (`pip install --upgrade isic-cli`) and give it a try, let me know if it works.

**Comment by nuzhat-promi** [comment]
Thank you for solving the issue. I was able to download the metadata without any problem. Sorry for the late reply.
